language: node_js
node_js:
    - "6"
    - "7"
    - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_script:
  - npm run coverall
after_success:
  - bash <(curl -s https://codecov.io/bash)
